### ISSUE TITLE
Integrating ADFS with omniauth-saml and devise is not working

### ISSUE THREAD

**Issue by mmsommer** [omniauth/omniauth-saml#102]
I am trying to integrate our ADFS login with our application which uses ActiveAdmin in combination with Devise. I succesfully added omniauth-saml for that purpose. The application now redirects to ADFS, the login succeeds but than fails on the callback. I get the error `Invalid ticket`.

When I try to look into the response on the server in the omniauth-saml lib I can see it says: `@document=<UNDEFINED> ... </>` and `@decrypted_document=<UNDEFINED> ... </>`

The `initializers/devise.rb` reads:

    config.omniauth :saml,
                    assertion_consumer_service_url: 'https://my_server/admin/auth/saml/callback',
                    issuer: 'https://my_server/',
                    authn_context: 'urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport',
                    idp_sso_target_url: 'https://my_adfs_server/adfs/ls/',
                    assertion_consumer_service_binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
                    assertion_consumer_logout_service_binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
                    idp_sso_target_url_runtime_params: {original_request_param: :mapped_idp_param},
                    name_identifier_format: 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',
                    idp_cert: idp_certificate,
                    request_attributes: {},
                    attribute_statements: {email: ['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress'],
                                           name: ['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name'],
                                           first_name: ['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname'],
                                           last_name: ['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname']},
                    private_key: sp_key,
                    certificate: sp_certificate,
                    security: {authn_requests_signed: true,
                               logout_requests_signed: true,
                               logout_responses_signed: true,
                               metadata_signed: true,
                               digest_method: XMLSecurity::Document::SHA1,
                               signature_method: XMLSecurity::Document::RSA_SHA1,
                               embed_sign: false}

How can I solve this?

**Addition:**
It appears that REXML::Document is unable to decrypt the Cypher inside of the SAML response. It fails to do so without errorring. When I try to do it myself by using https://www.samltool.com/decrypt.php I see no problems with it though.

**Comment by mmsommer** [comment]
Nevermind, it looks like I picked the wrong certificate from ADFS metadata

**Comment by leesmith** [comment]
@mmsommer If in my saml options, when integrating with ADFS, I'm using the `:idp_cert` option. From which certificate do I choose from the AD server do I use for this setting? I have nearly this same setup as yours but I can't get past the `Authentication failure! invalid_ticket: OneLogin::RubySaml::ValidationError, Fingerprint mismatch` error. My solution works perfectly with Google Gsuite however.

Thanks for any help!
