### ISSUE TITLE
Why do we need to validate the @name_id is present? 

### ISSUE THREAD

**Issue by jiongye** [omniauth/omniauth-saml#106]
I recent setup SAML authenticate with an IDP, they don't return a name_id field in their response.  So I ended up forting the gem and removed the name_id validation. I am wondering why we need to validate that if it is not required in the SAML protocol. 

```
if @name_id.nil? || @name_id.empty?
    raise OmniAuth::Strategies::SAML::ValidationError.new("SAML response missing 'name_id'")
end
```

**Comment by md5** [comment]
@jiongye `@name_id` is used as the `uid` in the OmniAuth metadata. I believe that's the source of this requirement. If it were to be removed, there would need to be some other mechanism to determine the intended `uid` for OmniAuth.

**Comment by jiongye** [comment]
@md5 If it is for the OmniAuth metadata, then it doesn't matter in the callback_phase, because we don't generate metadata in the callback phase. I mean we can still use the @name_id for the uid, we just don't force it to be present.

**Comment by md5** [comment]
@jiongye I'm not sure how `@name_id` can be used for the `uid` if we don't require it to be present. The OmniAuth auth hash schema requires `uid` to be present: https://github.com/intridea/omniauth/wiki/Auth-Hash-Schema#schema-10-and-later

**Comment by jiongye** [comment]
@md5  I think the intent for the uid is to identify the user that returned from the authentication service, in the case of SAML, it is the user identifier from the IDP response.  Unlike Twitter or facebook, or google authentication service, the return format is always the same for their own service, so they can set the uid to that field, the SAML IDPs can return the user identifier in different fields other than name_id and not breaking the SAML protocol, and that is the exact case to the IDP I connect to. It is good if they return the user identifier in the name_id field, if not, we can use the response_object in my pull request: https://github.com/omniauth/omniauth-saml/pull/107 to find the user identifier and map it to our local user. Let me know what you think?

**Comment by jiongye** [comment]
@md5 Also from the link you send above: "Fields marked required will always be present.", that only means those fields are always exist in the env['omniauth.auth'] variable, it doesn't mean they are always have values in them.

**Comment by md5** [comment]
@jiongye I think that's not the right reading of that wiki page. Take a look at the `valid?` method for the auth hash: https://github.com/intridea/omniauth/blob/1cc1cf4b2821a7d2a4a376a5ca93c61b6bd8b5f1/lib/omniauth/auth_hash.rb#L18

**Comment by jiongye** [comment]
@md5 Although the valid? method exist in the auth hash class, it never get used. Here: https://github.com/intridea/omniauth/blob/1cc1cf4b2821a7d2a4a376a5ca93c61b6bd8b5f1/lib/omniauth/strategy.rb#L332 

They even let you to skip info or other things in the auth hash. I think that is why when I removed the check on the @name_id, everything still works.

**Comment by pitbulk** [comment]
ruby-saml does not validated the presence of the nameID since is an optional SAML element.
In others toolkits like the [php](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Response.php#L388) or python there was a validation, but I made this validation optional.

At the end you need something to identify the user, but this can be retrieved from the nameID or from an Attribute of the AttributeStatement.

I used to give priority on the Attributes vs the NameID, like in this [Wordpress SAML plugin](https://github.com/onelogin/wordpress-saml/blob/master/onelogin-saml-sso/php/functions.php#L142)

So my suggestion:  Remove that validation and provide a way to let the user decide how get that uid.

**Comment by md5** [comment]
@pitbulk That sounds completely reasonable. Thanks for your insight and examples from other SAML integrations.

**Comment by ben-gilman** [comment]
@md5 Are you going to change this based on @pitbulk comments?  We do lots of SAML integrations and are constantly asking our customers to add a name_id field even though we never use it.

**Comment by md5** [comment]
@ben-gilman I wasn't planning on making the change myself, but I'd be happy to review a PR that makes this change.

**Comment by md5** [comment]
This code was removed in #137.
