### ISSUE TITLE
Support multiple signing keys

### ISSUE THREAD

**Issue by mceldeen** [omniauth/omniauth-saml#112]
According to section 2.4.1.1 of [Metadata for the OASIS Security Assertion Markup Language (SAML) V2.0 spec](https://www.oasis-open.org/committees/download.php/35391/sstc-saml-metadata-errata-2.0-wd-04-diff.pdf), multiple signing certs may be provided for a given IdP. This provider does not currently support this functionality. One reason this matters is because AzureAD via SAML 2.0 happens to use multiple signing certs which makes this gem incompatible with AzureAD.

This change would [require a change to the ruby-saml gem](https://github.com/onelogin/ruby-saml/issues/329) so this cannot be immediately implemented using the `ruby-saml` gem. However,  the discussion in the relevant pull request indicates that those changes will be made relatively soon (perhaps end of September 2016).

**Comment by md5** [comment]
This is now possible by upgrading to `ruby-saml` 1.4.3. Information on how to use multiple IdP certificates can be found in the `ruby-saml` documentation. In addition, information on how to configure the IdP certificates from an XML metadata file was added to the `README` in #135.
