### ISSUE TITLE
Error: app_not_configured_for_user with google apps

### ISSUE THREAD

**Issue by Fenntasy** [omniauth/omniauth-saml#116]
Hello,

I'm trying to use this gem with devise to log with google apps for business with their SAML protocol. Here is my conf

```ruby
  config.omniauth :saml,
      issuer: "my_app_id",
      idp_sso_target_url: "https://accounts.google.com/o/saml2/idp?idpid=#{GOOGLE_APP_ID}",
      idp_cert: '-----BEGIN CERTIFICATE-----
cuting for privacy
-----END CERTIFICATE-----',
      name_identifier_format: "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
```

I'm trying (if I understand correctly) to do a SP initiated connexion so I start with the url of my domain with `/auth/saml` that redirects me to the `idp_sso_target_url` and that's when I have the error 

> Error: app_not_configured_for_user

> Service is not configured for this user.

I can see that there is an AuthnRequest that's created in my logs 

```xml
[2016-09-22T08:39:45.412930 #26607] DEBUG -- : Created AuthnRequest: 
<samlp:AuthnRequest 
  AssertionConsumerServiceURL='https://mydomain.com/auth/saml/callback' 
  Destination='https://accounts.google.com/o/saml2?idpid=****' 
  ID='_********-****-****-****-************' 
  IssueInstant='2016-09-22T08:39:45Z' 
  Version='2.0' 
  xmlns:saml='urn:oasis:names:tc:SAML:2.0:assertion' 
  xmlns:samlp='urn:oasis:names:tc:SAML:2.0:protocol'>
<saml:Issuer>my_app_id</saml:Issuer>
<samlp:NameIDPolicy AllowCreate='true' Format='urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress'/>
</samlp:AuthnRequest>
```

Is there something I am missing, maybe you can point me in the right direction ?

**Comment by Fenntasy** [comment]
Resolved.

If someone has the problem one day, you need to set `URL ACS` in the google SAML App form to your callback url (yourdomain.com/auth/saml/callback by default).

**Comment by nattfodd** [comment]
Also, this error is happening when you have `issuer` and `Entity ID *` mismatch, they should be exactly the same.
