### ISSUE TITLE
Drop support for Ruby 1.9 and 2.0

### ISSUE THREAD

**Issue by md5** [omniauth/omniauth-saml#126]
It looks like `omniauth` has now dropped support for EOL versions of Ruby as of version 1.5.0. I think we should follow suit and only support Ruby 2.1 or higher. This should greatly simplify the Travis config.

cf. omniauth/omniauth#883

**Comment by md5** [comment]
If we make this change, I think we should also add `required_ruby_version` to the Gemspec so that it shows up properly on RubyGems.org and in the API.

**Comment by bufferoverflow** [comment]
+1
