### ISSUE TITLE
http://example.com/auth/saml/metadata - No route matches

### ISSUE THREAD

**Issue by RobertWSaunders** [omniauth/omniauth-saml#127]
Hey, 
I want to provide my idp with the metadata from my app (the sp), I try to go to http://example.com/auth/saml/metadata but there is no route configured? 

I am implementing this using Devise, the same issue is on StackOverflow from another user but there was never a solution: http://stackoverflow.com/questions/22232416/omniauth-saml-in-rails-route-not-found-error-for-auth-saml-metadata/26874370#26874370

What do I have to do in my routes.rb or configuration to get the metadata link for my SP?

**Comment by ilikepi** [comment]
In our app, which also uses Devise integration, we need to scope the path with the name of the resource (in our case, "users"): http://example.com/users/auth/saml/metadata

Give that a shot.  I will throw together a quick PR for the README file...

**Comment by RobertWSaunders** [comment]
Awesome that worked great, thank you for updating the documentation!
