### ISSUE TITLE
ruby-saml 1.4.3 breaks default assertion_consumer_service_url

### ISSUE THREAD

**Issue by justinhoward** [omniauth/omniauth-saml#139]
ruby-saml 1.4.3 added SubjectConfirmation Recipient validation. This means that assertion_consumer_service_url must be set in the ruby-saml settings during the callback_phase. Typically I depend on omniauth-saml to set this automatically. However, the default is not set during the callback phase, which causes a SubjectConfirmation Recipient validation failure.

Moving the line

```
options[:assertion_consumer_service_url] ||= callback_url
```

into `with_settings` seems to fix the issue. I was about to create a PR, but had trouble creating a spec since it it uses a Recipient of localhost, but a callback_url of example.org.

**Comment by md5** [comment]
Looks like this change was made in https://github.com/onelogin/ruby-saml/pull/397

**Comment by md5** [comment]
Your suggestion of moving the code that defaults `assertion_consumer_service_url` into `with_settings` sounds reasonable to me. To create a spec that passes, it seems reasonable to either change the `callback_url` in the specs to match what's in the response fixtures or to regenerate the fixtures.
