### ISSUE TITLE
Received 405 Response without Allow Header

### ISSUE THREAD

**Issue by tommybstitch** [omniauth/omniauth-saml#143]
I am trying to use this strategy to authenticate with SAP SuccessFactors, though when I go to `/auth/saml` I get `Received 405 Response without Allow Header`. 

Is there a way I can send along the `Allow` header with the initial authentication request?

**Comment by swarzech** [comment]
+1

**Comment by tommybstitch** [comment]
Closing due to the realization that this was user error and a lack of understanding about how SAP SuccessFactors authentication worked.
