### ISSUE TITLE
Infinite redirect loops when using `before_action authenticate_user!` in controller

### ISSUE THREAD

**Issue by slalomandrew** [omniauth/omniauth-saml#145]
Possibly just a chance of me being stupid, but I've followed the docs fairly religiously and found nothing. I've put details of my setup in an [SO post here](https://stackoverflow.com/questions/46414775/setting-up-saml-callback-in-rails-using-devise-and-omniauth-saml), but the gist of it is basically that my app isn't redirecting to the IDP to get creds. Instead, it seems to be redirecting to itself infinitely, causing an ERR_TOO_MANY_REDIRECTS.

**Comment by slalomandrew** [comment]
It looks like the issue here is that `user_saml_omniauth_authorize_path` is incorrectly redirecting to /users/auth/saml/callback.

**Comment by md5** [comment]
@slalomandrew That helper is generated by Devise, not OmniAuth itself or `omniauth-saml`. What does `bundle exec rake routes` say? It sounds like your routes are not configured correctly.

**Comment by slalomandrew** [comment]
It says a lot of things. Is there anything specific it *should* say? IE, a login path that might not exist and cause a redirect...?
