### ISSUE TITLE
SubjectConfirmation not parsing correctly?

### ISSUE THREAD

**Issue by slalomandrew** [omniauth/omniauth-saml#146]
It looks like I'm encountering [this issue](https://github.com/onelogin/ruby-saml/issues/399) in the underlying ruby-saml gem (1.4.3 specific, which is what omniauth-saml uses). Any suggestions for circumventing this, or passing the `skip_recipient_check` option down along to ruby-saml?

**Comment by duncanjbrown** [comment]
I've just encountered the same issue, and I solved it by adding

``` 
assertion_consumer_service_url: ENV['DOMAIN'] + '/auth/saml/callback'
```

to `config/omniauth.rb`. You'll need your own `ENV` var, obviously. I feel like there might be a better way to do this — a helper to generate that URL somewhere in Omniauth, perhaps?

**Comment by slalomandrew** [comment]
@duncanjbrown alas, I'm already setting the ACS URL in the omniauth section of my config/initializers/devise.rb

**Comment by duncanjbrown** [comment]
Ah, must be something else then. Hope you get there.

**Comment by pitbulk** [comment]
Can we require the settings.assertion_consumer_service_url to be properly set at omniauth?

**Comment by slalomandrew** [comment]
@duncanjbrown well - found the issue. There was a trailing slash in the env var where our ACS URL was being set and there was not one in the SubjectConfirmationData field. Problem solved there ;)

**Comment by duncanjbrown** [comment]
Aha! Excellent :)

**Comment by md5** [comment]
I believe this issue was fixed in https://github.com/omniauth/omniauth-saml/pull/140

**Comment by md5** [comment]
Please comment if we should reopen this.
