### ISSUE TITLE
Unable to upgrade to version 1.10.0

### ISSUE THREAD

**Issue by snehavas** [omniauth/omniauth-saml#162]
Hello,

We were unable to upgrade to version 1.10.0 (we were on 1.4.0).
To debug, we rolled back to our version 1.4.0 and started upgrading sequentially. We noticed that we safely upgraded to version 1.7(which has a internal dependency with ruby-saml 1.4.2). However when we upgrade to the next saml version (which has a ruby-saml dependency of 1.4.3), it starts breaking. We found the following error message in our logs (the same error we got when we directly upgraded to 1.10.0) -
Authentication failure! invalid_ticket: OneLogin::RubySaml::ValidationError, A valid SubjectConfirmation was not found on this Response

We tried giving a assertion_consumer_service_url (although ur documenation says its optional). However it failed saying its not a valid audience.

Any idea what might be the issue?

**Comment by md5** [comment]
It's related to this: https://github.com/onelogin/ruby-saml/issues/399

It was previously raised here as https://github.com/omniauth/omniauth-saml/issues/146, but my understanding at the time was that we had already fixed the issue in https://github.com/omniauth/omniauth-saml/pull/140

**Comment by viveksoundrapandi** [comment]
@md5 does omniauth-saml provide provision to enable skip_recipient_check option while initializing the OneLogin::RubySaml::Response class? 
Enabling the skip_recipient_check option  solved it for me

**Comment by viveksoundrapandi** [comment]
passing skip_recipient_check as parameter to omniauth-saml, will resolve the issue

**Comment by viveksoundrapandi** [comment]
@md5 when will the change of ruby-saml from 1.4 to 1.7 get released as gem? I could see it merged to the trunk but not yet released

**Comment by viveksoundrapandi** [comment]
@md5 any updates here?

**Comment by viveksoundrapandi** [comment]
@md5 is this released yet?  [](https://github.com/omniauth/omniauth-saml/commit/d530da47797030bc2c459ac8f3fe35a3a7d9c4b6)

**Comment by bzcorn** [comment]
@md5 is there any update on integrating this change?

**Comment by supernova32** [comment]
@viveksoundrapandi that commit has been on master for a while now, and was released as gem with the v1.10.1 version

**Comment by mberlanda** [comment]
once this PR https://github.com/omniauth/omniauth-saml/pull/165 pass, you should be able to inherit form `OneLogin::RubySaml::Response` the options to whitelist.

This was introduced in https://github.com/onelogin/ruby-saml/releases/tag/v1.8.0

**Comment by viveksoundrapandi** [comment]
guess this issue can be closed now, as the fix is available in 1.10.1
