### ISSUE TITLE
Could i pass user details from SP to IDP using <saml:Subject> element?

### ISSUE THREAD

**Issue by developerRohan** [omniauth/omniauth-saml#168]
I want to pass the user details in the saml request. I found on internet that i could do so by using <saml:Subject>  element. Please guide on this.

**Comment by smboykin** [comment]
It looks like this support was added in RubySaml 1.10.0 via the `name_identifier_value_requested` config parameter.  Any timetable on when the RubySaml dependency will be upgraded from 1.8.0?

**Comment by linda-le1** [comment]
Any updates on when the RubySaml dependency will be upgraded to at least 1.10?

**Comment by suprnova32** [comment]
@linda-le1 the version dependency specified in the `gemspec` file allows you to set your own version of `ruby-saml` to 1.10 and `omniauth-saml` will use that version. `~> 1.9` means that the dependency will be satisfied with a version that is >= 1.9 but < 2.0.
