### ISSUE TITLE
OmniAuth v2.0.0rc1

### ISSUE THREAD

**Issue by BobbyMcWho** [omniauth/omniauth-saml#196]
Hello, maintainer of OmniAuth here. 

I just wanted to make the maintainers of this gem aware of the discussion that I have opened regarding v2.0.0 of OmniAuth. I invite you to join in and voice any concerns you may have here: https://github.com/omniauth/omniauth/discussions/1017

**Comment by jonknapp** [comment]
If there are no concerns about allowing users to migrate beyond v1 omniauth, dropping `'~> 1.3',` from the gemspec will allow people to use the newly released omniauth v2 gem.

**Comment by BobbyMcWho** [comment]
I'll do some local testing and see if I can '>= 1.3', '< 3' with this gem as I have a few others, or if I need to go straight to '~> 2'
