### ISSUE TITLE
Wrong file permissions

### ISSUE THREAD

**Issue by ronnqvistandreas** [omniauth/omniauth-saml#226]
Since 2.2.0 and 2.1.1, the file permissions for `CHANGELOG.md` and `lib/omniauth-saml/version.rb` have changed from 644 to 600, making them not accessible by certain users (e.g. in a CI environment).

This occurs after installing the gem through `gem install omniauth-saml`, but not when cloning the repository from Github.

**Comment by bufferoverflow** [comment]
thanks for the report @ronnqvistandreas I published already a new gem version https://rubygems.org/gems/omniauth-saml/versions/2.2.1

**Comment by ronnqvistandreas** [comment]
Thanks for the quick response!
