### ISSUE TITLE
Version 2.1.1 breaks semantic versioning

### ISSUE THREAD

**Issue by chiragsinghal** [omniauth/omniauth-saml#228]
In patch version update from 2.1.0 to 2.1.1, ruby version requirement was modified from 2.4+ to 3.1+, this could be a breaking change for apps running on Ruby 3.0 or lower.
If possible, please consider including only the required security patch related changes in this patch version update instead of modifying the minimum ruby version requirements. Those who are on higher ruby version can use the 2.2.x versions already.

**Comment by bufferoverflow** [comment]
Just fixed that see https://github.com/omniauth/omniauth-saml/releases/tag/v2.1.2 , see https://rubygems.org/gems/omniauth-saml/versions/2.1.2

**Comment by chiragsinghal** [comment]
Thanks a lot for quick action
