### ISSUE TITLE
Is there going to a minor version patch for OmniAuth 1.0 to address Ruby SAML vulnerability

### ISSUE THREAD

**Issue by kli-instacart** [omniauth/omniauth-saml#229]
For the CVE issue highlighted by: GHSA-cvp8-5r8g-fhvq, regarding Ruby SAML vulnerability, are there plans to add a minor version bump to address the issue?

Our team relies on OmniAuth 1.0, but do not currently have bandwidth to undertake a major version bump. A minor patch would help bridge the gap.

**Comment by stephenpowers-sage** [comment]
According to dependobot alert, omniauth-saml has a v1.17 patch for this issue https://github.com/SAML-Toolkits/ruby-saml/security/advisories/GHSA-jw9c-mfg7-9rx2 but I see no tag for this. We are in the same position as @kli-instacart

**Comment by bufferoverflow** [comment]
Here you go https://github.com/omniauth/omniauth-saml/releases/tag/v1.10.4

**Comment by stephenpowers-sage** [comment]
Thanks @bufferoverflow much appreciated :)
