### ISSUE TITLE
Route not found error for /auth/saml/metadata

### ISSUE THREAD

**Issue by dandekar** [omniauth/omniauth-saml#24]
I have a routing question.

When I go to myserver.com/auth/saml/metadata, I get a routing error (No route matches). The only relevant route I have in routes.rb is /auth/:provider/callback. What route do I need to add to be able to access the metadata URL?

Thanks a lot!

**Comment by roughcompass** [comment]
experiencing a route error: No route matches [GET] "/auth/saml/metadata"

omniauth-saml 1.6.0
rails 4.2.5
