### ISSUE TITLE
Support additional SAML token fields in info hash

### ISSUE THREAD

**Issue by alim** [omniauth/omniauth-saml#28]
It would be useful to support additional SAML token fields in the info hash that is returned during the callback phase. In particular, the additional information to be included in the info hash could include:
- issuer 
- session_index
- session_not_on_or_after
- response.session_expires_at
- not_before
- not_on_or_after

These values are available from the ruby-saml gem [Response class](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/response.rb). I would be happy to supply a pull request with the corresponding code and test updates.

**Comment by md5** [comment]
The whole `Response` object is now available via `extra['response_object']`, available since version 1.7.0. See #107.
