### ISSUE TITLE
Trying to get SAML working.

### ISSUE THREAD

**Issue by netpenthe** [omniauth/omniauth-saml#59]
I'm trying to integrate against the Schoology Learning Management System

They are an iDP and I hit the link inside Schoology which is meant to send a SAML request to my Rails app and launch.

**When I hit the link a new page opens and it goes to:**
`http://schoology.xxx.com/apps/login/saml/initial?spentityid=822834723aa0dc7f209468fda2538a840561d576d&RelayState=http%3A%2F%2F127.0.0.1%3A3000%3Frealm%3Duser%26realm_id%3D28000593%26app_id%3D398907259%26is_ssl%3D0`

**And then a second later it redirects to:**
`http://schoology.xxx.com/oauth/authorize?SAMLRequest=fZHJasMwFEV%2FxTutZA12BkQcCM0mkG6Stotuiqy81iaW5OrJnb6%2BsktLsikSgofuPRykFWrb9WozxMYd4HUAjNkGEUJsvbvxDgcL4QjhrTVwf9hXpImxV4wJuch5WkIVnHMWQZsGAjKdQGxkMqO7rtbmTLJtgrZOj8S%2FPprG%2B86%2FfOYO3qN3%2BVnI3Op8QOYnxnj40H4ByXbbijwBFHVdl5zOyhNQLoqCiuJ5SfmSc7moT7KQ8xRFHGDnMGoXKyK5mFHBqSjvJFfjnj%2BS7CF5Tioy5yT7sJ1DNRpXZAhOeY0tKqctoIpGHTe3e5WCSv8%2BymWl%2F7%2FTBx%2B98R1Zr8a0muzC2upzUqBg%2BzbAil1e%2FUzX%2F7H%2BBg%3D%3D`

**And the error is given by this page as:**
`"Failed OAuth Request: Unknown request token"`

-------------------
**Meanwhile on my server i have:**
`Started POST "/teachers/auth/saml" for 127.0.0.1 at 2015-10-14 16:23:24 -0400
I, [2015-10-14T16:23:24.095349 #23024]  INFO -- omniauth: (saml) Request phase initiated.
  ActiveRecord::SessionStore::Session Load (0.6ms)  SELECT  "sessions".* FROM "sessions"  WHERE "sessions"."session_id" = '18c44423b06704b2994acb3cabfb3ad9'  ORDER BY "sessions"."id" ASC LIMIT 1`

`Created AuthnRequest: <samlp:AuthnRequest AssertionConsumerServiceURL='http://127.0.0.1:3000/teachers/auth/saml/callback' Destination='http://schoology.newton.k12.ma.us/oauth/authorize' ID=
'_57e06f00-54df-0133-13fc-080027bd2326' IssueInstant='2015-10-14T20:23:24Z' Version='2.0' xmlns:saml='urn:oasis:names:tc:SAML:2.0:assertion' xmlns:samlp='urn:oasis:names:tc:SAML:2.0:protoco
l'><saml:Issuer>makers-empire</saml:Issuer></samlp:AuthnRequest)`

**And then it seems to be putting a huge bunch of data into my session:**
`(0.1ms)  BEGIN  SQL (1.8ms)  UPDATE "sessions" SET "data" = $1, "updated_at" = $2 WHERE "sessions"."id" = 1  [["data", "BAh7B0kiFG9tbmlhdXRoLnBhcmFtcwY6BkVUewdJIhFTQU1MUmVzcG9uc2UG\nOwBUSSIC4CtQSE5oYld4d09sSmxjM0J2Ym5ObElIaHRiRzV6T25OaGJXeHdQ\nU0oxY200NmIyRnphWE02Ym1GdFpYTTZkR002VTBGTlREb3lMakE2Y0hKdmRH\nOWpiMndpS.... etc"`

**Is there something going wrong the base64 encoding here?  (I use a db store for sessions)**

Any help would be most appreciated.

I do **not** have a fingerprint or certificate in my config - would this cause this?

**Comment by bufferoverflow** [comment]
This seems to be a misconfiguration or related Schoology Learning Management System
