### ISSUE TITLE
Determine whether Ruby 1.8.7 should be supported

### ISSUE THREAD

**Issue by md5** [omniauth/omniauth-saml#70]
In #68, we were able to establish that Ruby 1.8.7 should probably work. When I run the specs locally, the Ruby 1.8 builds pass, but they are failing on Travis for some unknown reason.

Given that Ruby 1.8.7 was EOL'd in July 2014, it may not be worth maintaining compatibility. However, both `omniauth` and `ruby-saml` are making an effort to stay compatible with Ruby 1.8.7 and it doesn't seem to involve much of an effort (assuming the tests would pass), so it could be helpful to some users to keep things working for 1.8.7.

**Comment by md5** [comment]
If Ruby 1.8.7 compatibility is to be maintained, then https://github.com/omniauth/omniauth-saml/commit/e86725772f3d5ac11e6576f1935e72552ed99ee2 should be reverted.

**Comment by bufferoverflow** [comment]
I think we should remove ruby 1.8.7 support, it's EOL.

**Comment by supernova32** [comment]
I agree with removing support for 1.8.7. Even Ruby EE ended support for it in 2012 http://www.rubyenterpriseedition.com/
