### ISSUE TITLE
introduce Conventional Changelog

### ISSUE THREAD

**Issue by bufferoverflow** [omniauth/omniauth-saml#73]
What about using conventional changelog and generated [CHANGELOG.md](https://github.com/omniauth/omniauth-saml/blob/master/CHANGELOG.md) file from git commit messages? There is a gem to generate this: https://rubygems.org/gems/conventional-changelog

Some words about [Conventional Changelog](https://github.com/fossology/fossology/blob/master/CONTRIBUTING.md#git-commit-conventions) and why I believe it is a good thing:

-     directly see if a commit is a feature, fix, style change, etc.
-     become able to generate a useful CHANGELOG.md out from the git repo (issue trackers might change, but git history and commit messages stay)
-     many projects are using it, especially in the web, node.js area, e.g.
       -     Mozilla Accounts(fxa-xy)
       -     angular.js
       -     We use it internally on a platform and made very good experiences

Of course it requires a lot of discipline by the contributors, but from my experience on several OSS and internal projects, I can say it is really worth to use.

**Comment by md5** [comment]
My concern here would be noise. With a distributed development team, PRs tend to come in with a bunch of extraneous commits. To overcome this, contributors would have be be asked to squash and force-push their branches if the commits in their PRs don't make sense in a changelog format.

**Comment by bufferoverflow** [comment]
Yes, squash commits to one commit per change or feature becomes required.

However, this is best practice in many projects I work with and it ends up in a very clean commit history, easy to find relevant changes and to maintain code.

I've introduced it on several distributed projects with a lot of contribuitors, it was no problem at all. People adopted it very quickly and became familiar with the conventions, squash and force-push.

**Comment by bufferoverflow** [comment]
another reason why we need to automate this: https://github.com/intridea/omniauth/issues/756

I will prepare a CONTRIBUTING.md file.

**Comment by ilikepi** [comment]
Well, there definitely should be a file that tracks changes.  Whether this particular format is used or not seems less clear.  My personal preference is to not squash commits, because I think it deletes contextual information from the repository history that can be helpful.  That said, I'm probably biased by my experience, which is predominantly as a member of a small team working on a handful of projects.  The needs of an open source library may be different.

**Comment by supernova32** [comment]
I like the idea of having a CHANGELOG and I believe using conventional changelog can save us some headaches. I don't mind having to squash commits into one.

**Comment by md5** [comment]
My concerns about squashing are not so much for project members, but more for outside contributions.

**Comment by bufferoverflow** [comment]
I suggest to give it a try.

We can also add some more guidance to CONTRIBUTING.md or do a local ``git rebase --interactive HEAD~4`` and a ``git commit --amend`` before we commit.

**Comment by supernova32** [comment]
Contributing guidelines have been added, which detail the path for a conventional changelog. This issue can be closed
