### ISSUE TITLE
delete obsolete branches?

### ISSUE THREAD

**Issue by bufferoverflow** [omniauth/omniauth-saml#74]
Shall we delete these two branches?
* [0-9-1-dev](https://github.com/omniauth/omniauth-saml/tree/0-9-1-dev)
* [develop](https://github.com/omniauth/omniauth-saml/tree/develop)

**Comment by md5** [comment]
I think it's OK to delete `0-9-1-dev`. The functionality it was trying to support was added in https://github.com/onelogin/ruby-saml/commit/c2ecf7256dc8332e8508f77a50e9eee9942ef747

As for `develop`, I think that's more of a process question. I think with a more community-centric development model, a `develop` branch doesn't make as much sense, but I'm not opposed to keeping it as long as it it kept up-to-date.

I think a matter of more concern to me is to ensure that releases are getting tagged. It looks like 1.4.2 was pushed to RubyGems.org without being tagged here.

**Comment by supernova32** [comment]
@md5 that was my fault. I forgot to tag the release. I'll do that now.

Also, I'm in favor of deleting both branches.

**Comment by bufferoverflow** [comment]
@supernova32 thanks for tagging

I've just deleted the two branches.
