### ISSUE TITLE
Release 1.5?

### ISSUE THREAD

**Issue by supernova32** [omniauth/omniauth-saml#76]
A lot of changes have been merged that increase the functionality of this gem. I wonder if we are ready for 1.5.

@md5 @bufferoverflow @ilikepi what do you guys think?

**Comment by md5** [comment]
I was thinking the same thing, but I think #50 needs to be part of the release.

**Comment by supernova32** [comment]
@md5 makes sense. Let's also come to an agreement on #73 before releasing the new version.

**Comment by ilikepi** [comment]
Well, #50 is the last of the unmerged PRs I have in the custom branch we're using at work, so for selfish reasons I'd really love to get that resolved soon.  If holding back a 1.5.0 release helps to provide motivation, I am all for it. :grin:

**Comment by md5** [comment]
I've [pinged](https://github.com/omniauth/omniauth-saml/pull/50#issuecomment-182992596) @gmontard and @yasseur-vodeclic to update the PR for #50 to allow it to be merged.

**Comment by md5** [comment]
I've created https://github.com/omniauth/omniauth-saml/pull/82 to replace https://github.com/omniauth/omniauth-saml/pull/50

I think it's ready to merge.

**Comment by supernova32** [comment]
@md5 I merged #82. I think we are ready for 1.5 :smile:

**Comment by md5** [comment]
:+1:

**Comment by ilikepi** [comment]
In lieu of resolving #73, it would be helpful if the existing CHANGELOG could be brought up to date before the gem release.  I don't think I'll have time today to put together a PR for this unfortunately.

Otherwise, :+1: for 1.5!

**Comment by supernova32** [comment]
Yes, the CHANGELOG needs to be updated before we release 1.5

**Comment by md5** [comment]
If others are fine with using `conventional-changelog`, I don't consider my objections to be blocking. I'm also fine with merging #78 if there is consensus around the commit conventions. If the bar ends up being too high for outside contributions in practice, we can revisit the decision.

**Comment by bufferoverflow** [comment]
I suggest to merge #84 and #78 and switch to ``conventional-changelog`` after 1.5.0 release as suggested on #73 , search commit history to collect data for the CHANGELOG.md was a pain.

**Comment by crohr** [comment]
:+1: to release soon, especially to get #72. Thanks!

**Comment by supernova32** [comment]
I agree with the initial contributing guide in #78. They can be initial conventions and if they turn out to be to complicated for contributions from the community, we can updated them as we go. We should, though, have a document detailing our expectations from contributions. #78 is a great start.

**Comment by supernova32** [comment]
All outstanding pull requests have been merged. I'm starting the release process.

**Comment by supernova32** [comment]
After merging everything, updating the version files and fixing my mistakes that caused builds to error out, I see that the builds are failing. I'll need to investigate further what is causing them to fail. Until we are green again, the release will be halted.

I'll check on the failures after lunch.

**Comment by supernova32** [comment]
I found the error. While doing a `bundle install` the version for `ruby-saml` was updated to 1.1.2. This update broke something on the gem. I'm still investigating exactly what changed.

**Comment by supernova32** [comment]
OK, I found what broke, and it is stupidly simple. `ruby-saml` 1.1.2 now validates the destination of the SAML response. All our mock data was sending replies back to `localhost:9080` while on the test settings we set:

```ruby
 :assertion_consumer_service_url     => "http://localhost:3000/auth/saml/callback"
```

Changing that to:

```ruby
 :assertion_consumer_service_url     => "http://localhost:9080/auth/saml/callback"
```

fixed the failures, at least locally. I pushed a new branch to let Travis test.

**Comment by supernova32** [comment]
OK, v1.5.0 has been officially released :tada:

**Comment by bufferoverflow** [comment]
cool ... :sunglasses:!

Thanks @supernova32 !

**Comment by md5** [comment]
Nice! :dancers:

**Comment by ilikepi** [comment]
Yay! :sparkles:
