### ISSUE TITLE
Support single signout

### ISSUE THREAD

**Issue by Bandes** [omniauth/omniauth-saml#81]
I'm hoping to get single signout working with Omniauth-saml. My understanding is that ruby-saml supports this now, but as far as I can tell, this project does not. Is this something that could be added? (Or documented?)

**Comment by bufferoverflow** [comment]
Could you provide some more details on this, such as spec or documentation reference from ruby-saml?

**Comment by Bandes** [comment]
Sorry about that - here's the ruby-saml docs
https://github.com/onelogin/ruby-saml#single-log-out

**Comment by jkowens** [comment]
It would be awesome if this was implemented :+1:

**Comment by mlesb** [comment]
Another vote for single logout here.

**Comment by xinspire** [comment]
Would love it as well

**Comment by gpilla** [comment]
+1

I see that there is work in progress...
