### ISSUE TITLE
Add support for parsing remote IdP metadata

### ISSUE THREAD

**Issue by tomilaine** [omniauth/omniauth-saml#83]
Hi,

Is anyone working on adding the metadata exchange feature documented in:
https://github.com/onelogin/ruby-saml#metadata-based-configuration

Being able to parse the remote IdP metadata would help a lot in taking this library into use. Also the SP would be able to react to possible sudden changes in IdP metadata.

Tomi

**Comment by bufferoverflow** [comment]
I was not aware of the remote metadata feature, it would make setup much easier. I'm not aware of someone working on this, feel free to provide a Patch, see [CONTRIBUTING.md](https://github.com/omniauth/omniauth-saml/blob/master/CONTRIBUTING.md).

**Comment by sanderhahn** [comment]
At the moment i am parsing metadata and then extracting the `Settings` properties back into `env["omniauth.strategy"].options`. Configuration would be nicer if its possible to directly assign a `settings` property with `OneLogin::RubySaml::Settings` or a callback for retrieving the settings.

**Comment by rhoerbe** [comment]
A nice feature of the configuration-by-metadata is the option to do local idp-discovery, particularly if the IDP metadata has mdui_extensions provided.

**Comment by peterwake** [comment]
If anyone is looking to parse Microsoft federationmetadata.xml, I have written a gist that is quite rough and ready but gets you the key data you will need.. https://gist.github.com/peterwake/18349642f8f16397d1812461bac11aff
