### ISSUE TITLE
:request_attributes throws exception

### ISSUE THREAD

**Issue by Bandes** [omniauth/omniauth-saml#87]
If I put any value other than {} for `:request_attributes` I get the following error:

`no implicit conversion of Symbol into Integer`

Which looks like it's coming from ruby-saml, but I'm not sure.

**Comment by supernova32** [comment]
@Bandes can you share with us what you are using as `request_attributes`? If you look at the defaults for this option [here](https://github.com/omniauth/omniauth-saml/blob/master/lib/omniauth/strategies/saml.rb#L13) you'll see that it needs to be an array of hashes for it to work.

**Comment by Bandes** [comment]
I hadn't found that syntax, it is completely my mistake, thanks for the speedy answer and sorry for crying wolf.

**Comment by supernova32** [comment]
@Bandes don't worry about. Happy to help.
