### ISSUE TITLE
request to follow SemVer/mention it in README

### ISSUE THREAD

**Issue by pravi** [omniauth/omniauth-saml#93]
Like https://github.com/zombor/Validator/commit/b485289b45948ec3e829e8760b4221ee215931c9

**Comment by md5** [comment]
@pravi Regarding the "request to follow", do you think that `omniauth-saml` hasn't followed SemVer for the most recent release?

**Comment by pravi** [comment]
@md5 I maintain gitlab package in debian. Gitlab wants omniauth-saml ~> 1.4.0 and that will break if I upload omniauth-saml 1.5.0. If gitlab is confident 1.5 will not break their code, they can confidently declare omniauth-saml ~> 1.4. But as things stand right now, there is no clear statement. Do you think its realistic for gitlab to check over 260 gems how each of their previous releases were? SemVer makes life easy for users of libraries and I think every library should follow it and make it easy for people to find that information.

**Comment by supernova32** [comment]
@pravi what version of GitLab are you packaging? `omniauth-saml` was updated to 1.4.2 on version 8.4.4 and GitLab version 8.6 will make use of `omniauth-saml` 1.5.0. 

You can see the commit for 1.4.2 here: https://github.com/gitlabhq/gitlabhq/commit/ea7bdc78eed8db7ff4b5440b282678b1c5b021f7

and the commit 1.5.0 here: https://github.com/gitlabhq/gitlabhq/commit/32ddf092f3ca5cbb9fdb7b7b3754ba61495d0532

Please let us know where you think `omniauth-saml` has not followed the SemVer rules you mention.

**Comment by bufferoverflow** [comment]
I guess the thing @pravi likes to have is a clear commitment to semver principle and I agree with him we should mention this within the `README.md` to simplify life of software packagers and users.

I prepare a pull request for this.

**Comment by supernova32** [comment]
if all it takes is a simple mention of commitment, then sure, let's commit.

**Comment by pravi** [comment]
Yes, a mention of commitment is all I need.
